### PR TITLE
Remove asford from maintainers

### PR DESCRIPTION
**Pull request by asford**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by asford** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Sorry to see you leave, @asford. Do you want me to merge this?

**Comment by ngam** [comment]
(I am happy to take care of this feedstock for the time being, and you're welcome to stay inactive for as long as you want --- potentially you could become active again later. Just fyi)

**Comment by asford** [comment]
Our group has transitioned from `hub` to `gh`, so I won't be involved in this feedstock anymore.
Thank you for driving this going forward.

**Pull request merged**
