### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jakirkham**
Fix a typo in `dev_url` and use `https` in `home`.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by sodre** [comment]
@jakirkham, good catch and sorry about that.

Any desire to have that check added to the linter?

**Comment by jakirkham** [comment]
What checks exactly?

**Comment by sodre** [comment]
That curl of dev_url, doc_url and home return a 200, i.e. it would catch typos like the one I had.

**Comment by jakirkham** [comment]
Sounds reasonable. Please feel free to raise an issue over at conda-smithy about checking whether URLs can be visited.

**Pull request merged**
